apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: sandbox-vm01
  namespace: sandbox
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: sandbox-vm01
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
